const fs = require('fs');
const path = require('path');

// ดึงตัวแปรจาก Environment Variables (ของ Vercel)
const configContent = `// ================================================================
// Firebase Configuration — Generated by Build Script
// ================================================================
const FIREBASE_CONFIG = {
  apiKey: "${process.env.FIREBASE_API_KEY || ''}",
  authDomain: "${process.env.FIREBASE_AUTH_DOMAIN || ''}",
  projectId: "${process.env.FIREBASE_PROJECT_ID || ''}",
  storageBucket: "${process.env.FIREBASE_STORAGE_BUCKET || ''}",
  messagingSenderId: "${process.env.FIREBASE_MESSAGING_SENDER_ID || ''}",
  appId: "${process.env.FIREBASE_APP_ID || ''}"
};
`;

const targetDir = path.join(__dirname, 'model');
const targetFile = path.join(targetDir, 'firebase-config.js');

try {
  // ตรวจสอบว่ามีโฟลเดอร์ model หรือไม่
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }

  // เขียนไฟล์
  fs.writeFileSync(targetFile, configContent, 'utf8');
  console.log('✅ firebase-config.js has been generated successfully!');
} catch (error) {
  console.error('❌ Failed to generate firebase-config.js:', error);
  process.exit(1);
}
